server:
  port: 3000
spring:
  application:
    name: atguigu-crowd-redis
  redis:
    host: 192.168.84.131
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka